---
  - name: softwares installation
    hosts: all
    become: yes
    tasks: 
      - name: update the packages
        shell: sudo yum update –y
        
      - name: java installation
        shell: sudo amazon-linux-extras install java-openjdk11 -y
        #yum:
        #  name: amazon-linux-extras java-1.8.0-openjdk
        #  state: present
          
      - name: Download Long Term Jenkins release
        get_url:
          url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
          dest: /etc/yum.repos.d/jenkins.repo

      - name: Import jenkins key from url
        ansible.builtin.rpm_key:
          state: present
          key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

      - name: yum update
        yum:
          name: '*'
          state: latest
        
      - name: Install jenkins
        yum:
          name: jenkins
          state: latest

      - name: daemon-reload to pick up config changes
        ansible.builtin.systemd:
          daemon_reload: yes

      #- name: Start jenkins
      #  ansible.builtin.systemd:
      #    service: jenkins
      #    state: started
      - name: Start jenkins
        service: name=jenkins state=started enabled=yes
